export type LedgerStatus = "in_stock" | "sold" | "returned" | "disposed";

export type LedgerItem = {
  id: number;
  managementNo: string;
  sourceOrderNo: string;
  saleOrderNo: string;
  category: string;
  itemName: string;
  description: string;
  quantity: number;
  acquiredAt: string;
  purchaseType: string;
  acquiredFrom: string;
  sellerIdentification: string;
  sellerAddress: string;
  sellerName: string;
  sellerAge: string;
  sellerOccupation: string;
  purchasePrice: number;
  soldAt: string;
  soldTo: string;
  saleType: string;
  salePrice: number;
  saleAmount: number;
  saleCurrency: string;
  buyerCountry: string;
  buyerId: string;
  buyerName: string;
  buyerCity: string;
  buyerState: string;
  buyerPostalCode: string;
  buyerAddress1: string;
  buyerAddress2: string;
  buyerAddress3: string;
  trackingNo: string;
  shippingSite: string;
  status: LedgerStatus;
};
