import { buildEcSalesViewRecords } from "@/lib/ecSales";
import type {
  ShopeeExchangeRate,
  ShopeePayment,
  ShopeePurchase,
  ShopeeSupplier,
} from "@/types/ecSales";

const ecSalesSamplePurchases: ShopeePurchase[] = [
  {
    sku: "20260116_miyawaki_03",
    account: "ph",
    orderNo: "2603034XVYYYSK",
    soldAt: "2026-03-03",
    firstChatAt: "",
    purchasedAt: "2026-03-09",
    country: "フィリピン",
    saleAmount: "PHP3,361.00",
    purchasedFlag: "FALSE",
    purchasePrice: "¥6,300",
    domesticShippingFee: "¥1,135",
    slsShippingFee: "PHP706.00",
    points: "45P",
    note: "",
    packer: "松本3/10",
    actualWeightG: "1887",
    lengthCm: "44",
    widthCm: "19",
    heightCm: "2/1",
    sizeMemo: "96",
    shippingChatAt: "",
    itemName:
      "Ichiban Kuji JoJo's Bizarre Adventure Stardust Crusaders DIO MASTERLISE Prize C Anime Figure",
    supplierName: "トレファク",
    receiptPrintedAt: "",
    domesticTrackingNo: "2790-9218-3156",
    slsTrackingNo: "PH2601416162482",
    yamatoSlipFlag: "TRUE",
    bundledWith: "",
    balanceCheckedFlag: "TRUE",
  },
  {
    sku: "20260302_ishida_02",
    account: "ph",
    orderNo: "260304861KD5C7",
    soldAt: "2026-03-04",
    firstChatAt: "",
    purchasedAt: "2026-03-04",
    country: "フィリピン",
    saleAmount: "PHP3,747.00",
    purchasedFlag: "FALSE",
    purchasePrice: "¥7,700",
    domesticShippingFee: "¥613",
    slsShippingFee: "PHP181.00",
    points: "308P",
    note: "",
    packer: "3/5小栁",
    actualWeightG: "",
    lengthCm: "",
    widthCm: "",
    heightCm: "",
    sizeMemo: "0",
    shippingChatAt: "",
    itemName:
      "S.H.Figuarts Funeral of Freiren Freiren (Resale Version) Approximately 140mm PVC & ABS Painted Movable Figure TAMASHII NATIONS",
    supplierName: "Amazon",
    receiptPrintedAt: "2026-05-07",
    domesticTrackingNo: "2790-9158-1506",
    slsTrackingNo: "PH263189613027K",
    yamatoSlipFlag: "TRUE",
    bundledWith: "",
    balanceCheckedFlag: "TRUE",
  },
  {
    sku: "20260219_machida_01",
    account: "sg",
    orderNo: "260305C5P0E9RJ",
    soldAt: "2026-03-05",
    firstChatAt: "",
    purchasedAt: "2026-03-06",
    country: "シンガポール",
    saleAmount: "SGD194.18",
    purchasedFlag: "FALSE",
    purchasePrice: "¥13,800",
    domesticShippingFee: "¥1,135",
    slsShippingFee: "SGD54.98",
    points: "",
    note: "",
    packer: "松本3/9",
    actualWeightG: "5598",
    lengthCm: "45",
    widthCm: "36",
    heightCm: "1/15",
    sizeMemo: "97",
    shippingChatAt: "",
    itemName: "training pad 12 inches with stand TS12S",
    supplierName: "SOUND HOUSE",
    receiptPrintedAt: "2026-03-09",
    domesticTrackingNo: "2790-9207-6012",
    slsTrackingNo: "SG261870660942O",
    yamatoSlipFlag: "TRUE",
    bundledWith: "",
    balanceCheckedFlag: "FALSE",
  },
];

const ecSalesSampleSuppliers: ShopeeSupplier[] = [
  {
    rowNo: "6",
    sku: "20260116_miyawaki_03",
    orderNo: "2603034XVYYYSK",
    account: "ph",
    soldAt: "2026-03-03",
    purchasedAt: "2026-03-09",
    country: "フィリピン",
    mag: "",
    saleAmount: "PHP3,361.00",
    purchasePrice: "¥6,300",
    shippingActualYen: "PHP706.00",
    pointsNote: "45P",
    shippingNote: "",
    packer: "松本3/10",
    shippingService: "",
    weightG: "1887",
    appliedWeightG: "",
    lengthCm: "44",
    widthCm: "19",
    heightCm: "2/1",
    itemName:
      "Ichiban Kuji JoJo's Bizarre Adventure Stardust Crusaders DIO MASTERLISE Prize C Anime Figure",
    supplierName: "トレファク",
    firstMailAt: "",
    receiptPrintedAt: "",
  },
  {
    rowNo: "7",
    sku: "20260302_ishida_02",
    orderNo: "260304861KD5C7",
    account: "ph",
    soldAt: "2026-03-04",
    purchasedAt: "2026-03-04",
    country: "フィリピン",
    mag: "",
    saleAmount: "PHP3,747.00",
    purchasePrice: "¥7,700",
    shippingActualYen: "PHP181.00",
    pointsNote: "308P",
    shippingNote: "",
    packer: "3/5小栁",
    shippingService: "",
    weightG: "",
    appliedWeightG: "",
    lengthCm: "",
    widthCm: "",
    heightCm: "",
    itemName:
      "S.H.Figuarts Funeral of Freiren Freiren (Resale Version) Approximately 140mm PVC & ABS Painted Movable Figure TAMASHII NATIONS",
    supplierName: "Amazon",
    firstMailAt: "",
    receiptPrintedAt: "2026-05-07",
  },
  {
    rowNo: "8",
    sku: "20260219_machida_01",
    orderNo: "260305C5P0E9RJ",
    account: "sg",
    soldAt: "2026-03-05",
    purchasedAt: "2026-03-06",
    country: "シンガポール",
    mag: "",
    saleAmount: "SGD194.18",
    purchasePrice: "¥13,800",
    shippingActualYen: "SGD54.98",
    pointsNote: "",
    shippingNote: "",
    packer: "松本3/9",
    shippingService: "",
    weightG: "5598",
    appliedWeightG: "",
    lengthCm: "45",
    widthCm: "36",
    heightCm: "1/15",
    itemName: "training pad 12 inches with stand TS12S",
    supplierName: "SOUND HOUSE",
    firstMailAt: "",
    receiptPrintedAt: "2026-03-09",
  },
];

const ecSalesSamplePayments: ShopeePayment[] = [
  {
    orderId: "2603034XVYYYSK",
    buyerUsername: "haallouu",
    orderCreatedAt: "2026-03-03",
    paymentMethod: "Cash on Delivery",
    paymentMethodDetails: "",
    installmentPlan: "",
    transactionFeeRate: "2.24%",
    payoutCompletedAt: "2026-06-03",
    originalProductPrice: "PHP3,361.00",
    sellerPromotion: "",
    refundAmount: "",
    shopeeRebate: "",
    sellerVoucher: "",
    cofundVoucher: "",
    sellerCoinCashback: "",
    cofundCoinCashback: "",
    buyerPaidShippingFee: "",
    shippingFeeRebate: "PHP100.00",
    definedShippingFee: "-PHP706.00",
    reverseShippingFee: "",
    returnToSellerShippingFee: "",
    shippingFeeSupportSavings: "",
    amsCommissionFee: "",
    commissionFee: "-PHP347.00",
    logisticsFailDeliveryFee: "",
    logisticsReturnRefundFee: "",
    serviceFee: "-PHP300.00",
    supportProgramFee: "",
    transactionFee: "-PHP75.00",
    fbsFee: "",
    totalReleasedAmount: "PHP2,554.00",
    sellerVoucherCode: "",
    lostCompensation: "",
    estimatedOrderWeight: "0.02",
    sellerShippingPromotion: "",
    shippingProvider: "Standard International",
    courierName: "Standard International",
    cashRefundToBuyerAmount: "",
    returnRefundCoinOffset: "",
    returnRefundShopeeVoucherOffset: "",
    returnRefundBankPromoOffset: "",
    returnRefundPaymentChannelPromoOffset: "",
    region: "ph",
    currency: "PHP",
  },
  {
    orderId: "260304861KD5C7",
    buyerUsername: "raemberioso",
    orderCreatedAt: "2026-03-04",
    paymentMethod: "Cash on Delivery",
    paymentMethodDetails: "",
    installmentPlan: "",
    transactionFeeRate: "2.24%",
    payoutCompletedAt: "2026-06-03",
    originalProductPrice: "PHP3,747.00",
    sellerPromotion: "",
    refundAmount: "",
    shopeeRebate: "",
    sellerVoucher: "",
    cofundVoucher: "",
    sellerCoinCashback: "",
    cofundCoinCashback: "",
    buyerPaidShippingFee: "",
    shippingFeeRebate: "PHP50.00",
    definedShippingFee: "-PHP181.00",
    reverseShippingFee: "",
    returnToSellerShippingFee: "",
    shippingFeeSupportSavings: "",
    amsCommissionFee: "",
    commissionFee: "-PHP375.00",
    logisticsFailDeliveryFee: "",
    logisticsReturnRefundFee: "",
    serviceFee: "",
    supportProgramFee: "",
    transactionFee: "-PHP84.00",
    fbsFee: "",
    totalReleasedAmount: "PHP2,843.00",
    sellerVoucherCode: "",
    lostCompensation: "",
    estimatedOrderWeight: "0.01",
    sellerShippingPromotion: "",
    shippingProvider: "Standard International",
    courierName: "Standard International",
    cashRefundToBuyerAmount: "",
    returnRefundCoinOffset: "",
    returnRefundShopeeVoucherOffset: "",
    returnRefundBankPromoOffset: "",
    returnRefundPaymentChannelPromoOffset: "",
    region: "ph",
    currency: "PHP",
  },
  {
    orderId: "260305C5P0E9RJ",
    buyerUsername: "psyche.sumilang",
    orderCreatedAt: "2026-03-05",
    paymentMethod: "Credit / Debit Card",
    paymentMethodDetails: "",
    installmentPlan: "",
    transactionFeeRate: "2.24%",
    payoutCompletedAt: "2026-06-03",
    originalProductPrice: "SGD194.18",
    sellerPromotion: "",
    refundAmount: "",
    shopeeRebate: "",
    sellerVoucher: "",
    cofundVoucher: "",
    sellerCoinCashback: "",
    cofundCoinCashback: "",
    buyerPaidShippingFee: "",
    shippingFeeRebate: "",
    definedShippingFee: "-SGD54.98",
    reverseShippingFee: "",
    returnToSellerShippingFee: "",
    shippingFeeSupportSavings: "",
    amsCommissionFee: "",
    commissionFee: "-SGD28.06",
    logisticsFailDeliveryFee: "",
    logisticsReturnRefundFee: "",
    serviceFee: "",
    supportProgramFee: "",
    transactionFee: "-SGD5.83",
    fbsFee: "",
    totalReleasedAmount: "SGD194.18",
    sellerVoucherCode: "",
    lostCompensation: "",
    estimatedOrderWeight: "0.03",
    sellerShippingPromotion: "",
    shippingProvider: "Doorstep Delivery",
    courierName: "Doorstep Delivery",
    cashRefundToBuyerAmount: "",
    returnRefundCoinOffset: "",
    returnRefundShopeeVoucherOffset: "",
    returnRefundBankPromoOffset: "",
    returnRefundPaymentChannelPromoOffset: "",
    region: "sg",
    currency: "SGD",
  },
];

const ecSalesSampleExchangeRates: ShopeeExchangeRate[] = [
  {
    rateDate: "2026-03-03",
    usd: 157.51,
    gbp: 211.16,
    eur: 184.13,
    cad: 115.22,
    aud: 111.88,
    php: 2.71,
    sgd: 123.74,
    brl: 30.46,
  },
  {
    rateDate: "2026-03-04",
    usd: 157.7,
    gbp: 210.25,
    eur: 182.82,
    cad: 115.24,
    aud: 110.56,
    php: 2.7,
    sgd: 123.41,
    brl: 29.88,
  },
  {
    rateDate: "2026-03-05",
    usd: 156.61,
    gbp: 209.62,
    eur: 182.34,
    cad: 114.84,
    aud: 110.93,
    php: 2.68,
    sgd: 122.94,
    brl: 29.94,
  },
  {
    rateDate: "2026-06-03",
    usd: 0,
    gbp: 0,
    eur: 0,
    cad: 0,
    aud: 0,
    php: 2.62,
    sgd: 121.4,
    brl: 0,
  },
];

export const ecSalesSampleRecords = buildEcSalesViewRecords(
  ecSalesSamplePurchases,
  ecSalesSampleSuppliers,
  ecSalesSamplePayments,
  ecSalesSampleExchangeRates,
);
